# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUIBnsxoO.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import Icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(858, 670)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setTabShape(QTabWidget.Triangular)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet(u"background-color: rgb(24, 24, 36);")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.mainHeader = QFrame(self.centralwidget)
        self.mainHeader.setObjectName(u"mainHeader")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.mainHeader.sizePolicy().hasHeightForWidth())
        self.mainHeader.setSizePolicy(sizePolicy1)
        self.mainHeader.setMaximumSize(QSize(16777215, 100))
        self.mainHeader.setStyleSheet(u"background-color: rgb(9, 5, 13);")
        self.mainHeader.setFrameShape(QFrame.Box)
        self.mainHeader.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.mainHeader)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.leftHeader = QFrame(self.mainHeader)
        self.leftHeader.setObjectName(u"leftHeader")
        self.leftHeader.setFrameShape(QFrame.NoFrame)
        self.leftHeader.setFrameShadow(QFrame.Raised)
        self.gridLayout = QGridLayout(self.leftHeader)
        self.gridLayout.setObjectName(u"gridLayout")
        self.icon = QLabel(self.leftHeader)
        self.icon.setObjectName(u"icon")
        self.icon.setFrameShape(QFrame.NoFrame)
        self.icon.setPixmap(QPixmap(u":/icons/Icons/airplay_1.svg"))
        self.icon.setScaledContents(False)

        self.gridLayout.addWidget(self.icon, 0, 0, 1, 1)


        self.horizontalLayout.addWidget(self.leftHeader)

        self.centralHeader = QFrame(self.mainHeader)
        self.centralHeader.setObjectName(u"centralHeader")
        sizePolicy2 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.centralHeader.sizePolicy().hasHeightForWidth())
        self.centralHeader.setSizePolicy(sizePolicy2)
        self.centralHeader.setFrameShape(QFrame.NoFrame)
        self.centralHeader.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.centralHeader)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.name = QLabel(self.centralHeader)
        self.name.setObjectName(u"name")
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(9, 5, 13, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush2 = QBrush(QColor(120, 120, 120, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.name.setPalette(palette)
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setTextFormat(Qt.AutoText)
        self.name.setWordWrap(False)

        self.horizontalLayout_3.addWidget(self.name, 0, Qt.AlignHCenter)


        self.horizontalLayout.addWidget(self.centralHeader)

        self.rightHeader = QFrame(self.mainHeader)
        self.rightHeader.setObjectName(u"rightHeader")
        self.rightHeader.setFrameShape(QFrame.NoFrame)
        self.rightHeader.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.rightHeader)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 5, 0)
        self.minimizeButton = QPushButton(self.rightHeader)
        self.minimizeButton.setObjectName(u"minimizeButton")
        icon1 = QIcon()
        icon1.addFile(u":/icons/Icons/arrow-down-left.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.minimizeButton.setIcon(icon1)

        self.horizontalLayout_2.addWidget(self.minimizeButton)

        self.closeButton = QPushButton(self.rightHeader)
        self.closeButton.setObjectName(u"closeButton")
        icon2 = QIcon()
        icon2.addFile(u":/icons/Icons/x.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.closeButton.setIcon(icon2)

        self.horizontalLayout_2.addWidget(self.closeButton)


        self.horizontalLayout.addWidget(self.rightHeader)


        self.verticalLayout.addWidget(self.mainHeader)

        self.Central = QFrame(self.centralwidget)
        self.Central.setObjectName(u"Central")
        sizePolicy.setHeightForWidth(self.Central.sizePolicy().hasHeightForWidth())
        self.Central.setSizePolicy(sizePolicy)
        self.Central.setAutoFillBackground(False)
        self.Central.setFrameShape(QFrame.Box)
        self.Central.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.Central)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.menu = QFrame(self.Central)
        self.menu.setObjectName(u"menu")
        sizePolicy1.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy1)
        self.menu.setMinimumSize(QSize(0, 0))
        self.menu.setMaximumSize(QSize(0, 16777215))
        self.menu.setStyleSheet(u"background-color: rgb(9, 5, 13);")
        self.menu.setFrameShape(QFrame.Box)
        self.menu.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_7 = QHBoxLayout(self.menu)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.stackedToolsMenu = QStackedWidget(self.menu)
        self.stackedToolsMenu.setObjectName(u"stackedToolsMenu")
        self.penPage = QWidget()
        self.penPage.setObjectName(u"penPage")
        self.verticalLayout_3 = QVBoxLayout(self.penPage)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.PENlabel = QLabel(self.penPage)
        self.PENlabel.setObjectName(u"PENlabel")
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.PENlabel.setPalette(palette1)
        font1 = QFont()
        font1.setPointSize(16)
        font1.setBold(True)
        font1.setItalic(True)
        font1.setUnderline(True)
        font1.setWeight(75)
        self.PENlabel.setFont(font1)
        self.PENlabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_3.addWidget(self.PENlabel)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.penSizeLabel = QLabel(self.penPage)
        self.penSizeLabel.setObjectName(u"penSizeLabel")
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.penSizeLabel.setPalette(palette2)
        font2 = QFont()
        font2.setPointSize(14)
        self.penSizeLabel.setFont(font2)

        self.horizontalLayout_8.addWidget(self.penSizeLabel)

        self.penSizeSlider = QSlider(self.penPage)
        self.penSizeSlider.setObjectName(u"penSizeSlider")
        self.penSizeSlider.setMinimum(5)
        self.penSizeSlider.setMaximum(25)
        self.penSizeSlider.setOrientation(Qt.Horizontal)

        self.horizontalLayout_8.addWidget(self.penSizeSlider)

        self.penSizeLCD = QLCDNumber(self.penPage)
        self.penSizeLCD.setObjectName(u"penSizeLCD")
        self.penSizeLCD.setDigitCount(2)
        self.penSizeLCD.setSegmentStyle(QLCDNumber.Filled)
        self.penSizeLCD.setProperty("value", 5.000000000000000)
        self.penSizeLCD.setProperty("intValue", 5)

        self.horizontalLayout_8.addWidget(self.penSizeLCD)


        self.verticalLayout_3.addLayout(self.horizontalLayout_8)

        self.horizontalLayout_22 = QFrame(self.penPage)
        self.horizontalLayout_22.setObjectName(u"horizontalLayout_22")
        self.horizontalLayout_22.setMinimumSize(QSize(100, 100))
        self.horizontalLayout_22.setFrameShape(QFrame.StyledPanel)
        self.horizontalLayout_22.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_9 = QHBoxLayout(self.horizontalLayout_22)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.penSizeLabel_2 = QLabel(self.horizontalLayout_22)
        self.penSizeLabel_2.setObjectName(u"penSizeLabel_2")
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.penSizeLabel_2.setPalette(palette3)
        self.penSizeLabel_2.setFont(font2)

        self.horizontalLayout_9.addWidget(self.penSizeLabel_2)

        self.colorPickerFrame = QFrame(self.horizontalLayout_22)
        self.colorPickerFrame.setObjectName(u"colorPickerFrame")
        sizePolicy3 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.colorPickerFrame.sizePolicy().hasHeightForWidth())
        self.colorPickerFrame.setSizePolicy(sizePolicy3)
        self.colorPickerFrame.setMinimumSize(QSize(200, 200))
        self.colorPickerFrame.setStyleSheet(u"\n"
"border: 5px solid ;\n"
"border-radius: 100px;\n"
"border-style: outset;\n"
"padding: 5px;\n"
"\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:270, stop:0 rgba(255, 0, 0, 255), stop:0.17 rgba(255, 0, 255, 255), stop:0.33 rgba(0, 0, 255, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.66 rgba(0, 255, 0, 255), stop:0.83 rgba(255, 255, 0, 255), stop:1 rgba(255, 0, 0, 255));")
        self.colorPickerFrame.setFrameShape(QFrame.NoFrame)
        self.colorPickerFrame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_12 = QVBoxLayout(self.colorPickerFrame)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.penColorDial = QDial(self.colorPickerFrame)
        self.penColorDial.setObjectName(u"penColorDial")
        self.penColorDial.setStyleSheet(u"")
        self.penColorDial.setMaximum(359)
        self.penColorDial.setValue(0)
        self.penColorDial.setSliderPosition(0)
        self.penColorDial.setOrientation(Qt.Horizontal)
        self.penColorDial.setWrapping(True)
        self.penColorDial.setNotchTarget(120.000000000000000)
        self.penColorDial.setNotchesVisible(True)

        self.verticalLayout_12.addWidget(self.penColorDial)


        self.horizontalLayout_9.addWidget(self.colorPickerFrame)


        self.verticalLayout_3.addWidget(self.horizontalLayout_22)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_3.addItem(self.verticalSpacer)

        self.stackedToolsMenu.addWidget(self.penPage)
        self.eraserPage = QWidget()
        self.eraserPage.setObjectName(u"eraserPage")
        self.verticalLayout_4 = QVBoxLayout(self.eraserPage)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.frame = QFrame(self.eraserPage)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_5 = QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.ERASERlabel = QLabel(self.frame)
        self.ERASERlabel.setObjectName(u"ERASERlabel")
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.ERASERlabel.setPalette(palette4)
        self.ERASERlabel.setFont(font1)
        self.ERASERlabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_5.addWidget(self.ERASERlabel)

        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.eraserSizeLabel = QLabel(self.frame)
        self.eraserSizeLabel.setObjectName(u"eraserSizeLabel")
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.eraserSizeLabel.setPalette(palette5)
        self.eraserSizeLabel.setFont(font2)

        self.horizontalLayout_10.addWidget(self.eraserSizeLabel)

        self.eraserSizeSlider = QSlider(self.frame)
        self.eraserSizeSlider.setObjectName(u"eraserSizeSlider")
        self.eraserSizeSlider.setMinimum(5)
        self.eraserSizeSlider.setMaximum(25)
        self.eraserSizeSlider.setOrientation(Qt.Horizontal)

        self.horizontalLayout_10.addWidget(self.eraserSizeSlider)

        self.eraserSizeLCD = QLCDNumber(self.frame)
        self.eraserSizeLCD.setObjectName(u"eraserSizeLCD")
        self.eraserSizeLCD.setDigitCount(2)
        self.eraserSizeLCD.setSegmentStyle(QLCDNumber.Filled)
        self.eraserSizeLCD.setProperty("value", 5.000000000000000)
        self.eraserSizeLCD.setProperty("intValue", 5)

        self.horizontalLayout_10.addWidget(self.eraserSizeLCD)


        self.verticalLayout_5.addLayout(self.horizontalLayout_10)

        self.eraseAllButton = QPushButton(self.frame)
        self.eraseAllButton.setObjectName(u"eraseAllButton")
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.eraseAllButton.setPalette(palette6)
        self.eraseAllButton.setFont(font2)

        self.verticalLayout_5.addWidget(self.eraseAllButton)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_5.addItem(self.verticalSpacer_2)


        self.verticalLayout_4.addWidget(self.frame)

        self.stackedToolsMenu.addWidget(self.eraserPage)
        self.shapesPage = QWidget()
        self.shapesPage.setObjectName(u"shapesPage")
        self.verticalLayout_6 = QVBoxLayout(self.shapesPage)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.frame_2 = QFrame(self.shapesPage)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.SHAPESLabel = QLabel(self.frame_2)
        self.SHAPESLabel.setObjectName(u"SHAPESLabel")
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.SHAPESLabel.setPalette(palette7)
        self.SHAPESLabel.setFont(font1)
        self.SHAPESLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_7.addWidget(self.SHAPESLabel)

        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.shapesThicknesslabel = QLabel(self.frame_2)
        self.shapesThicknesslabel.setObjectName(u"shapesThicknesslabel")
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.shapesThicknesslabel.setPalette(palette8)
        self.shapesThicknesslabel.setFont(font2)

        self.horizontalLayout_11.addWidget(self.shapesThicknesslabel)

        self.shapesThicknessSlider = QSlider(self.frame_2)
        self.shapesThicknessSlider.setObjectName(u"shapesThicknessSlider")
        self.shapesThicknessSlider.setMinimum(5)
        self.shapesThicknessSlider.setMaximum(25)
        self.shapesThicknessSlider.setOrientation(Qt.Horizontal)

        self.horizontalLayout_11.addWidget(self.shapesThicknessSlider)

        self.shapesThicknessLCD = QLCDNumber(self.frame_2)
        self.shapesThicknessLCD.setObjectName(u"shapesThicknessLCD")
        self.shapesThicknessLCD.setDigitCount(2)
        self.shapesThicknessLCD.setSegmentStyle(QLCDNumber.Filled)
        self.shapesThicknessLCD.setProperty("value", 5.000000000000000)
        self.shapesThicknessLCD.setProperty("intValue", 5)

        self.horizontalLayout_11.addWidget(self.shapesThicknessLCD)


        self.verticalLayout_7.addLayout(self.horizontalLayout_11)

        self.horizontalLayout_13 = QHBoxLayout()
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.shapeLabel = QLabel(self.frame_2)
        self.shapeLabel.setObjectName(u"shapeLabel")
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.shapeLabel.setPalette(palette9)
        self.shapeLabel.setFont(font2)

        self.horizontalLayout_13.addWidget(self.shapeLabel)

        self.CircleButton = QToolButton(self.frame_2)
        self.CircleButton.setObjectName(u"CircleButton")
        sizePolicy.setHeightForWidth(self.CircleButton.sizePolicy().hasHeightForWidth())
        self.CircleButton.setSizePolicy(sizePolicy)
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.CircleButton.setPalette(palette10)
        self.CircleButton.setFont(font2)
        icon3 = QIcon()
        icon3.addFile(u":/icons/Icons/circle.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.CircleButton.setIcon(icon3)
        self.CircleButton.setIconSize(QSize(64, 64))
        self.CircleButton.setCheckable(True)
        self.CircleButton.setChecked(True)

        self.horizontalLayout_13.addWidget(self.CircleButton)

        self.LineButton = QToolButton(self.frame_2)
        self.LineButton.setObjectName(u"LineButton")
        sizePolicy.setHeightForWidth(self.LineButton.sizePolicy().hasHeightForWidth())
        self.LineButton.setSizePolicy(sizePolicy)
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.LineButton.setPalette(palette11)
        self.LineButton.setFont(font2)
        icon4 = QIcon()
        icon4.addFile(u":/icons/Icons/Line.png", QSize(), QIcon.Normal, QIcon.Off)
        self.LineButton.setIcon(icon4)
        self.LineButton.setIconSize(QSize(64, 64))
        self.LineButton.setCheckable(True)

        self.horizontalLayout_13.addWidget(self.LineButton)

        self.RectangleButton = QToolButton(self.frame_2)
        self.RectangleButton.setObjectName(u"RectangleButton")
        sizePolicy.setHeightForWidth(self.RectangleButton.sizePolicy().hasHeightForWidth())
        self.RectangleButton.setSizePolicy(sizePolicy)
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette12.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.RectangleButton.setPalette(palette12)
        self.RectangleButton.setFont(font2)
        icon5 = QIcon()
        icon5.addFile(u":/icons/Icons/square_1.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.RectangleButton.setIcon(icon5)
        self.RectangleButton.setIconSize(QSize(64, 64))
        self.RectangleButton.setCheckable(True)

        self.horizontalLayout_13.addWidget(self.RectangleButton)


        self.verticalLayout_7.addLayout(self.horizontalLayout_13)

        self.frame_5 = QFrame(self.frame_2)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_12 = QHBoxLayout(self.frame_5)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.shapeLabel_2 = QLabel(self.frame_5)
        self.shapeLabel_2.setObjectName(u"shapeLabel_2")
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.shapeLabel_2.setPalette(palette13)
        self.shapeLabel_2.setFont(font2)

        self.horizontalLayout_12.addWidget(self.shapeLabel_2)

        self.shapesColorPickerFrame = QFrame(self.frame_5)
        self.shapesColorPickerFrame.setObjectName(u"shapesColorPickerFrame")
        sizePolicy3.setHeightForWidth(self.shapesColorPickerFrame.sizePolicy().hasHeightForWidth())
        self.shapesColorPickerFrame.setSizePolicy(sizePolicy3)
        self.shapesColorPickerFrame.setMinimumSize(QSize(200, 200))
        self.shapesColorPickerFrame.setStyleSheet(u"\n"
"border: 5px solid ;\n"
"border-radius: 100px;\n"
"border-style: outset;\n"
"padding: 5px;\n"
"\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:270, stop:0 rgba(255, 0, 0, 255), stop:0.17 rgba(255, 0, 255, 255), stop:0.33 rgba(0, 0, 255, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.66 rgba(0, 255, 0, 255), stop:0.83 rgba(255, 255, 0, 255), stop:1 rgba(255, 0, 0, 255));")
        self.shapesColorPickerFrame.setFrameShape(QFrame.NoFrame)
        self.shapesColorPickerFrame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_15 = QVBoxLayout(self.shapesColorPickerFrame)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.shapesColorDial = QDial(self.shapesColorPickerFrame)
        self.shapesColorDial.setObjectName(u"shapesColorDial")
        self.shapesColorDial.setStyleSheet(u"")
        self.shapesColorDial.setMaximum(359)
        self.shapesColorDial.setValue(0)
        self.shapesColorDial.setSliderPosition(0)
        self.shapesColorDial.setOrientation(Qt.Horizontal)
        self.shapesColorDial.setWrapping(True)
        self.shapesColorDial.setNotchTarget(120.000000000000000)
        self.shapesColorDial.setNotchesVisible(True)

        self.verticalLayout_15.addWidget(self.shapesColorDial)


        self.horizontalLayout_12.addWidget(self.shapesColorPickerFrame)


        self.verticalLayout_7.addWidget(self.frame_5)

        self.verticalSpacer_3 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_7.addItem(self.verticalSpacer_3)


        self.verticalLayout_6.addWidget(self.frame_2)

        self.stackedToolsMenu.addWidget(self.shapesPage)
        self.textPage = QWidget()
        self.textPage.setObjectName(u"textPage")
        self.verticalLayout_8 = QVBoxLayout(self.textPage)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.frame_3 = QFrame(self.textPage)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.verticalLayout_9 = QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.TEXTLabel = QLabel(self.frame_3)
        self.TEXTLabel.setObjectName(u"TEXTLabel")
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette14.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.TEXTLabel.setPalette(palette14)
        self.TEXTLabel.setFont(font1)
        self.TEXTLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_9.addWidget(self.TEXTLabel)

        self.horizontalLayout_14 = QHBoxLayout()
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.textSizeLabel = QLabel(self.frame_3)
        self.textSizeLabel.setObjectName(u"textSizeLabel")
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette15.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette15.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette15.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette15.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.textSizeLabel.setPalette(palette15)
        self.textSizeLabel.setFont(font2)

        self.horizontalLayout_14.addWidget(self.textSizeLabel)

        self.textSizeSlider = QSlider(self.frame_3)
        self.textSizeSlider.setObjectName(u"textSizeSlider")
        self.textSizeSlider.setMinimum(5)
        self.textSizeSlider.setMaximum(25)
        self.textSizeSlider.setOrientation(Qt.Horizontal)

        self.horizontalLayout_14.addWidget(self.textSizeSlider)

        self.textSizeLCD = QLCDNumber(self.frame_3)
        self.textSizeLCD.setObjectName(u"textSizeLCD")
        self.textSizeLCD.setDigitCount(2)
        self.textSizeLCD.setSegmentStyle(QLCDNumber.Filled)
        self.textSizeLCD.setProperty("value", 5.000000000000000)
        self.textSizeLCD.setProperty("intValue", 5)

        self.horizontalLayout_14.addWidget(self.textSizeLCD)


        self.verticalLayout_9.addLayout(self.horizontalLayout_14)

        self.frame_6 = QFrame(self.frame_3)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_24 = QHBoxLayout(self.frame_6)
        self.horizontalLayout_24.setObjectName(u"horizontalLayout_24")
        self.shapeLabel_4 = QLabel(self.frame_6)
        self.shapeLabel_4.setObjectName(u"shapeLabel_4")
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette16.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette16.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette16.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette16.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette16.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette16.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette16.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.shapeLabel_4.setPalette(palette16)
        self.shapeLabel_4.setFont(font2)

        self.horizontalLayout_24.addWidget(self.shapeLabel_4)

        self.textColorPickerFrame = QFrame(self.frame_6)
        self.textColorPickerFrame.setObjectName(u"textColorPickerFrame")
        sizePolicy3.setHeightForWidth(self.textColorPickerFrame.sizePolicy().hasHeightForWidth())
        self.textColorPickerFrame.setSizePolicy(sizePolicy3)
        self.textColorPickerFrame.setMinimumSize(QSize(200, 200))
        self.textColorPickerFrame.setStyleSheet(u"\n"
"border: 5px solid ;\n"
"border-radius: 100px;\n"
"border-style: outset;\n"
"padding: 5px;\n"
"\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:270, stop:0 rgba(255, 0, 0, 255), stop:0.17 rgba(255, 0, 255, 255), stop:0.33 rgba(0, 0, 255, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.66 rgba(0, 255, 0, 255), stop:0.83 rgba(255, 255, 0, 255), stop:1 rgba(255, 0, 0, 255));")
        self.textColorPickerFrame.setFrameShape(QFrame.NoFrame)
        self.textColorPickerFrame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_17 = QVBoxLayout(self.textColorPickerFrame)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName(u"verticalLayout_17")
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.textColorDial = QDial(self.textColorPickerFrame)
        self.textColorDial.setObjectName(u"textColorDial")
        self.textColorDial.setStyleSheet(u"")
        self.textColorDial.setMaximum(359)
        self.textColorDial.setValue(0)
        self.textColorDial.setSliderPosition(0)
        self.textColorDial.setOrientation(Qt.Horizontal)
        self.textColorDial.setWrapping(True)
        self.textColorDial.setNotchTarget(120.000000000000000)
        self.textColorDial.setNotchesVisible(True)

        self.verticalLayout_17.addWidget(self.textColorDial)


        self.horizontalLayout_24.addWidget(self.textColorPickerFrame)


        self.verticalLayout_9.addWidget(self.frame_6)

        self.verticalSpacer_4 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_9.addItem(self.verticalSpacer_4)


        self.verticalLayout_8.addWidget(self.frame_3)

        self.stackedToolsMenu.addWidget(self.textPage)
        self.laserPage = QWidget()
        self.laserPage.setObjectName(u"laserPage")
        self.verticalLayout_10 = QVBoxLayout(self.laserPage)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.frame_4 = QFrame(self.laserPage)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.verticalLayout_11 = QVBoxLayout(self.frame_4)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.LASERLabel = QLabel(self.frame_4)
        self.LASERLabel.setObjectName(u"LASERLabel")
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette17.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette17.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette17.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette17.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette17.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette17.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette17.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.LASERLabel.setPalette(palette17)
        self.LASERLabel.setFont(font1)
        self.LASERLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_11.addWidget(self.LASERLabel)

        self.horizontalLayout_16 = QHBoxLayout()
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.laserSizeLabel = QLabel(self.frame_4)
        self.laserSizeLabel.setObjectName(u"laserSizeLabel")
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette18.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette18.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette18.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette18.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette18.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette18.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.laserSizeLabel.setPalette(palette18)
        self.laserSizeLabel.setFont(font2)

        self.horizontalLayout_16.addWidget(self.laserSizeLabel)

        self.laserSizeSlider = QSlider(self.frame_4)
        self.laserSizeSlider.setObjectName(u"laserSizeSlider")
        self.laserSizeSlider.setMinimum(5)
        self.laserSizeSlider.setMaximum(25)
        self.laserSizeSlider.setOrientation(Qt.Horizontal)

        self.horizontalLayout_16.addWidget(self.laserSizeSlider)

        self.laserSizeLCD = QLCDNumber(self.frame_4)
        self.laserSizeLCD.setObjectName(u"laserSizeLCD")
        self.laserSizeLCD.setDigitCount(2)
        self.laserSizeLCD.setSegmentStyle(QLCDNumber.Filled)
        self.laserSizeLCD.setProperty("value", 5.000000000000000)
        self.laserSizeLCD.setProperty("intValue", 5)

        self.horizontalLayout_16.addWidget(self.laserSizeLCD)


        self.verticalLayout_11.addLayout(self.horizontalLayout_16)

        self.frame_7 = QFrame(self.frame_4)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_15 = QHBoxLayout(self.frame_7)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.shapeLabel_5 = QLabel(self.frame_7)
        self.shapeLabel_5.setObjectName(u"shapeLabel_5")
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette19.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette19.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette19.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette19.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette19.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette19.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette19.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette19.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.shapeLabel_5.setPalette(palette19)
        self.shapeLabel_5.setFont(font2)

        self.horizontalLayout_15.addWidget(self.shapeLabel_5)

        self.laserColorPickerFrame = QFrame(self.frame_7)
        self.laserColorPickerFrame.setObjectName(u"laserColorPickerFrame")
        sizePolicy3.setHeightForWidth(self.laserColorPickerFrame.sizePolicy().hasHeightForWidth())
        self.laserColorPickerFrame.setSizePolicy(sizePolicy3)
        self.laserColorPickerFrame.setMinimumSize(QSize(200, 200))
        self.laserColorPickerFrame.setStyleSheet(u"\n"
"border: 5px solid ;\n"
"border-radius: 100px;\n"
"border-style: outset;\n"
"padding: 5px;\n"
"\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:270, stop:0 rgba(255, 0, 0, 255), stop:0.17 rgba(255, 0, 255, 255), stop:0.33 rgba(0, 0, 255, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.66 rgba(0, 255, 0, 255), stop:0.83 rgba(255, 255, 0, 255), stop:1 rgba(255, 0, 0, 255));")
        self.laserColorPickerFrame.setFrameShape(QFrame.NoFrame)
        self.laserColorPickerFrame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_18 = QVBoxLayout(self.laserColorPickerFrame)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName(u"verticalLayout_18")
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.laserColorDial = QDial(self.laserColorPickerFrame)
        self.laserColorDial.setObjectName(u"laserColorDial")
        self.laserColorDial.setStyleSheet(u"")
        self.laserColorDial.setMaximum(359)
        self.laserColorDial.setValue(0)
        self.laserColorDial.setSliderPosition(0)
        self.laserColorDial.setOrientation(Qt.Horizontal)
        self.laserColorDial.setWrapping(True)
        self.laserColorDial.setNotchTarget(120.000000000000000)
        self.laserColorDial.setNotchesVisible(True)

        self.verticalLayout_18.addWidget(self.laserColorDial)


        self.horizontalLayout_15.addWidget(self.laserColorPickerFrame)


        self.verticalLayout_11.addWidget(self.frame_7)

        self.verticalSpacer_5 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_11.addItem(self.verticalSpacer_5)


        self.verticalLayout_10.addWidget(self.frame_4)

        self.stackedToolsMenu.addWidget(self.laserPage)

        self.horizontalLayout_7.addWidget(self.stackedToolsMenu)


        self.horizontalLayout_4.addWidget(self.menu)

        self.centralRight = QFrame(self.Central)
        self.centralRight.setObjectName(u"centralRight")
        self.centralRight.setFrameShape(QFrame.Box)
        self.centralRight.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.centralRight)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(10, 0, 0, 0)
        self.toolsHeader = QFrame(self.centralRight)
        self.toolsHeader.setObjectName(u"toolsHeader")
        self.toolsHeader.setMinimumSize(QSize(0, 100))
        self.toolsHeader.setFrameShape(QFrame.Panel)
        self.toolsHeader.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.toolsHeader)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.menuButton = QToolButton(self.toolsHeader)
        self.menuButton.setObjectName(u"menuButton")
        sizePolicy4 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.menuButton.sizePolicy().hasHeightForWidth())
        self.menuButton.setSizePolicy(sizePolicy4)
        icon6 = QIcon()
        icon6.addFile(u":/icons/Icons/align-left.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.menuButton.setIcon(icon6)
        self.menuButton.setIconSize(QSize(32, 32))

        self.horizontalLayout_5.addWidget(self.menuButton, 0, Qt.AlignLeft)

        self.Tools = QFrame(self.toolsHeader)
        self.Tools.setObjectName(u"Tools")
        sizePolicy5 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.Tools.sizePolicy().hasHeightForWidth())
        self.Tools.setSizePolicy(sizePolicy5)
        self.Tools.setFrameShape(QFrame.StyledPanel)
        self.Tools.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_6 = QHBoxLayout(self.Tools)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.penButton = QToolButton(self.Tools)
        self.penButton.setObjectName(u"penButton")
        sizePolicy5.setHeightForWidth(self.penButton.sizePolicy().hasHeightForWidth())
        self.penButton.setSizePolicy(sizePolicy5)
        icon7 = QIcon()
        icon7.addFile(u":/icons/Icons/Pen.png", QSize(), QIcon.Normal, QIcon.Off)
        self.penButton.setIcon(icon7)
        self.penButton.setIconSize(QSize(64, 64))
        self.penButton.setCheckable(True)
        self.penButton.setChecked(True)

        self.horizontalLayout_6.addWidget(self.penButton)

        self.eraserButton = QToolButton(self.Tools)
        self.eraserButton.setObjectName(u"eraserButton")
        sizePolicy5.setHeightForWidth(self.eraserButton.sizePolicy().hasHeightForWidth())
        self.eraserButton.setSizePolicy(sizePolicy5)
        icon8 = QIcon()
        icon8.addFile(u":/icons/Icons/Eraser.png", QSize(), QIcon.Normal, QIcon.Off)
        self.eraserButton.setIcon(icon8)
        self.eraserButton.setIconSize(QSize(64, 64))
        self.eraserButton.setCheckable(True)

        self.horizontalLayout_6.addWidget(self.eraserButton)

        self.shapesButton = QToolButton(self.Tools)
        self.shapesButton.setObjectName(u"shapesButton")
        sizePolicy5.setHeightForWidth(self.shapesButton.sizePolicy().hasHeightForWidth())
        self.shapesButton.setSizePolicy(sizePolicy5)
        icon9 = QIcon()
        icon9.addFile(u":/icons/Icons/Shapes.png", QSize(), QIcon.Normal, QIcon.Off)
        self.shapesButton.setIcon(icon9)
        self.shapesButton.setIconSize(QSize(64, 64))
        self.shapesButton.setCheckable(True)

        self.horizontalLayout_6.addWidget(self.shapesButton)

        self.textButton = QToolButton(self.Tools)
        self.textButton.setObjectName(u"textButton")
        sizePolicy5.setHeightForWidth(self.textButton.sizePolicy().hasHeightForWidth())
        self.textButton.setSizePolicy(sizePolicy5)
        icon10 = QIcon()
        icon10.addFile(u":/icons/Icons/Text.png", QSize(), QIcon.Normal, QIcon.Off)
        self.textButton.setIcon(icon10)
        self.textButton.setIconSize(QSize(64, 64))
        self.textButton.setCheckable(True)

        self.horizontalLayout_6.addWidget(self.textButton)

        self.laserButton = QToolButton(self.Tools)
        self.laserButton.setObjectName(u"laserButton")
        sizePolicy5.setHeightForWidth(self.laserButton.sizePolicy().hasHeightForWidth())
        self.laserButton.setSizePolicy(sizePolicy5)
        icon11 = QIcon()
        icon11.addFile(u":/icons/Icons/Laser.png", QSize(), QIcon.Normal, QIcon.Off)
        self.laserButton.setIcon(icon11)
        self.laserButton.setIconSize(QSize(64, 64))
        self.laserButton.setCheckable(True)

        self.horizontalLayout_6.addWidget(self.laserButton)

        self.broadcastButton = QToolButton(self.Tools)
        self.broadcastButton.setObjectName(u"broadcastButton")
        sizePolicy5.setHeightForWidth(self.broadcastButton.sizePolicy().hasHeightForWidth())
        self.broadcastButton.setSizePolicy(sizePolicy5)
        icon12 = QIcon()
        icon12.addFile(u":/icons/Icons/video.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.broadcastButton.setIcon(icon12)
        self.broadcastButton.setIconSize(QSize(64, 64))
        self.broadcastButton.setCheckable(False)

        self.horizontalLayout_6.addWidget(self.broadcastButton)


        self.horizontalLayout_5.addWidget(self.Tools)


        self.verticalLayout_2.addWidget(self.toolsHeader, 0, Qt.AlignTop)

        self.centralCentral = QFrame(self.centralRight)
        self.centralCentral.setObjectName(u"centralCentral")
        sizePolicy5.setHeightForWidth(self.centralCentral.sizePolicy().hasHeightForWidth())
        self.centralCentral.setSizePolicy(sizePolicy5)
        self.centralCentral.setFrameShape(QFrame.Panel)
        self.centralCentral.setFrameShadow(QFrame.Raised)
        self.gridLayout_3 = QGridLayout(self.centralCentral)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.videoLabel = QLabel(self.centralCentral)
        self.videoLabel.setObjectName(u"videoLabel")
        palette20 = QPalette()
        brush3 = QBrush(QColor(24, 24, 36, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette20.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette20.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette20.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette20.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette20.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette20.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette20.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette20.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette20.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.videoLabel.setPalette(palette20)
        self.videoLabel.setScaledContents(False)

        self.gridLayout_3.addWidget(self.videoLabel, 0, 0, 1, 1)


        self.verticalLayout_2.addWidget(self.centralCentral)

        self.bottomCentral = QFrame(self.centralRight)
        self.bottomCentral.setObjectName(u"bottomCentral")
        self.bottomCentral.setFrameShape(QFrame.Panel)
        self.bottomCentral.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_18 = QHBoxLayout(self.bottomCentral)
        self.horizontalLayout_18.setObjectName(u"horizontalLayout_18")
        self.horizontalLayout_17 = QHBoxLayout()
        self.horizontalLayout_17.setObjectName(u"horizontalLayout_17")
        self.bottomStatusLabel = QLabel(self.bottomCentral)
        self.bottomStatusLabel.setObjectName(u"bottomStatusLabel")
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette21.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette21.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette21.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette21.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette21.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette21.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette21.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette21.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.bottomStatusLabel.setPalette(palette21)
        font3 = QFont()
        font3.setPointSize(12)
        self.bottomStatusLabel.setFont(font3)

        self.horizontalLayout_17.addWidget(self.bottomStatusLabel)

        self.useStatus = QLabel(self.bottomCentral)
        self.useStatus.setObjectName(u"useStatus")
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette22.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette22.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette22.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette22.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette22.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette22.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette22.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette22.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette22.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette22.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette22.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.useStatus.setPalette(palette22)
        font4 = QFont()
        font4.setPointSize(10)
        self.useStatus.setFont(font4)

        self.horizontalLayout_17.addWidget(self.useStatus)

        self.label_3 = QLabel(self.bottomCentral)
        self.label_3.setObjectName(u"label_3")
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette23.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette23.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette23.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette23.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette23.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette23.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette23.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette23.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette23.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette23.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette23.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.label_3.setPalette(palette23)
        font5 = QFont()
        font5.setPointSize(14)
        font5.setBold(True)
        font5.setItalic(False)
        font5.setUnderline(False)
        font5.setWeight(75)
        font5.setStrikeOut(False)
        self.label_3.setFont(font5)

        self.horizontalLayout_17.addWidget(self.label_3)

        self.videoStatusLabel = QLabel(self.bottomCentral)
        self.videoStatusLabel.setObjectName(u"videoStatusLabel")
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette24.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette24.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette24.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette24.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette24.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette24.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette24.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette24.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette24.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette24.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette24.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.videoStatusLabel.setPalette(palette24)
        self.videoStatusLabel.setFont(font4)

        self.horizontalLayout_17.addWidget(self.videoStatusLabel)


        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_18.addItem(self.horizontalSpacer_2)

        self.horizontalLayout_19 = QHBoxLayout()
        self.horizontalLayout_19.setObjectName(u"horizontalLayout_19")
        self.bottomColorLabel = QLabel(self.bottomCentral)
        self.bottomColorLabel.setObjectName(u"bottomColorLabel")
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette25.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette25.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette25.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette25.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette25.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette25.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette25.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette25.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette25.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette25.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette25.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.bottomColorLabel.setPalette(palette25)
        self.bottomColorLabel.setFont(font3)

        self.horizontalLayout_19.addWidget(self.bottomColorLabel)

        self.bottomCurrentColorButton = QToolButton(self.bottomCentral)
        self.bottomCurrentColorButton.setObjectName(u"bottomCurrentColorButton")
        self.bottomCurrentColorButton.setEnabled(False)
        self.bottomCurrentColorButton.setStyleSheet(u"background-color: rgb(255, 0, 0);")

        self.horizontalLayout_19.addWidget(self.bottomCurrentColorButton)


        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_18.addItem(self.horizontalSpacer)

        self.horizontalLayout_20 = QHBoxLayout()
        self.horizontalLayout_20.setObjectName(u"horizontalLayout_20")
        self.bottomCurrentSizeLabel = QLabel(self.bottomCentral)
        self.bottomCurrentSizeLabel.setObjectName(u"bottomCurrentSizeLabel")
        palette26 = QPalette()
        palette26.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette26.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette26.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette26.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette26.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette26.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette26.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette26.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette26.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette26.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette26.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette26.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.bottomCurrentSizeLabel.setPalette(palette26)
        self.bottomCurrentSizeLabel.setFont(font3)

        self.horizontalLayout_20.addWidget(self.bottomCurrentSizeLabel)

        self.bottomCurrentSizeLCD = QLCDNumber(self.bottomCentral)
        self.bottomCurrentSizeLCD.setObjectName(u"bottomCurrentSizeLCD")
        self.bottomCurrentSizeLCD.setDigitCount(2)
        self.bottomCurrentSizeLCD.setProperty("intValue", 5)

        self.horizontalLayout_20.addWidget(self.bottomCurrentSizeLCD)


        self.horizontalLayout_18.addLayout(self.horizontalLayout_20)


        self.verticalLayout_2.addWidget(self.bottomCentral)


        self.horizontalLayout_4.addWidget(self.centralRight)


        self.verticalLayout.addWidget(self.Central)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedToolsMenu.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.icon.setText("")
        self.name.setText(QCoreApplication.translate("MainWindow", u"Virtual Whiteboard", None))
        self.minimizeButton.setText("")
        self.closeButton.setText("")
        self.PENlabel.setText(QCoreApplication.translate("MainWindow", u"PEN", None))
        self.penSizeLabel.setText(QCoreApplication.translate("MainWindow", u"Size:", None))
        self.penSizeLabel_2.setText(QCoreApplication.translate("MainWindow", u"Color:", None))
        self.ERASERlabel.setText(QCoreApplication.translate("MainWindow", u"ERASER", None))
        self.eraserSizeLabel.setText(QCoreApplication.translate("MainWindow", u"Size:", None))
        self.eraseAllButton.setText(QCoreApplication.translate("MainWindow", u"ERASE INK ON SCREEN", None))
        self.SHAPESLabel.setText(QCoreApplication.translate("MainWindow", u"SHAPES", None))
        self.shapesThicknesslabel.setText(QCoreApplication.translate("MainWindow", u"Thickness", None))
        self.shapeLabel.setText(QCoreApplication.translate("MainWindow", u"Shape:", None))
        self.CircleButton.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.LineButton.setText(QCoreApplication.translate("MainWindow", u"L", None))
        self.RectangleButton.setText(QCoreApplication.translate("MainWindow", u"R", None))
        self.shapeLabel_2.setText(QCoreApplication.translate("MainWindow", u"Color:", None))
        self.TEXTLabel.setText(QCoreApplication.translate("MainWindow", u"TEXT", None))
        self.textSizeLabel.setText(QCoreApplication.translate("MainWindow", u"Size:", None))
        self.shapeLabel_4.setText(QCoreApplication.translate("MainWindow", u"Color:", None))
        self.LASERLabel.setText(QCoreApplication.translate("MainWindow", u"LASER", None))
        self.laserSizeLabel.setText(QCoreApplication.translate("MainWindow", u"Size:", None))
        self.shapeLabel_5.setText(QCoreApplication.translate("MainWindow", u"Color:", None))
        self.menuButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.penButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.eraserButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.shapesButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.textButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.laserButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.broadcastButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.videoLabel.setText(QCoreApplication.translate("MainWindow", u"VIDEO", None))
        self.bottomStatusLabel.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.useStatus.setText(QCoreApplication.translate("MainWindow", u"Inactive", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"|", None))
        self.videoStatusLabel.setText(QCoreApplication.translate("MainWindow", u"Full Video Broadcast", None))
        self.bottomColorLabel.setText(QCoreApplication.translate("MainWindow", u"Color:", None))
        self.bottomCurrentColorButton.setText("")
        self.bottomCurrentSizeLabel.setText(QCoreApplication.translate("MainWindow", u"Size:", None))
    # retranslateUi

